import React from "react";
import type { Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
          <SidebarProvider>
            <AppSidebar />
        <main className="">
            <SidebarTrigger />
            {children}
        </main>
          </SidebarProvider>
      </body>
    </html>
  );
}
