import React from "react";
import type { Metadata } from "next";
import { Sidebar } from "@/components/Sidebar";
import "../globals.css"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='antialiased'
      >
        <div className="flex h-screen">
          {/* Sidebar */}
          <Sidebar />
          
          {/* Main Content */}
          <main className="flex-1 bg-gray-50 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
