import React from "react";
import type { Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import MobileNav from "@/components/MobileNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
      <main className="flex h-header w-full font-inter bg-slate-100">
        <Sidebar/>
        <div className="flex size-full flex-col">
            <div className="flex h-16 items-center justify-between p-5 shadow-creditCard sm:p-8 md:hidden">
                <MobileNav/>
            </div>
        {children}
        </div>
    </main>
       
      </body>
    </html>
  );
}
